export { default as Blog } from "./Blog";
export { default as Contact } from "./Contact";
export { default as Home } from "./Home";
export { default as Logo } from "./Logo";
export { default as Services } from "./Services";
export { default as Tarifs } from "./Tarifs";
export { default as Reservation } from "./Reservation";
export { default as Search } from "./Search";
export { default as Connection } from "./Connection";
